from django.db import migrations, models

def create_countires(apps, schema_editor):
    Country = apps.get_model("accounts", "Country")
    Country.objects.bulk_create([
        Country(code='AF', name='Afghanistan'),
        Country(code='AL', name='Albania'),
        Country(code='DZ', name='Algeria'),
        Country(code='AS', name='American Samoa'),
        Country(code='AD', name='Andorra'),
        Country(code='AO', name='Angola'),
        Country(code='AI', name='Anguilla'),
        Country(code='AQ', name='Antarctica'),
        Country(code='AG', name='Antigua And Barbuda'),
        Country(code='AR', name='Argentina'),
        Country(code='AM', name='Armenia'),
        Country(code='AW', name='Aruba'),
        Country(code='AU', name='Australia'),
        Country(code='AT', name='Austria'),
        Country(code='AZ', name='Azerbaijan'),
        Country(code='BS', name='Bahamas'),
        Country(code='BH', name='Bahrain'),
        Country(code='BD', name='Bangladesh'),
        Country(code='BB', name='Barbados'),
        Country(code='BY', name='Belarus'),
        Country(code='BE', name='Belgium'),
        Country(code='BZ', name='Belize'),
        Country(code='BJ', name='Benin'),
        Country(code='BM', name='Bermuda'),
        Country(code='BT', name='Bhutan'),
        Country(code='BO', name='Bolivia'),
        Country(code='BA', name='Bosnia And Herzegowina'),
        Country(code='BW', name='Botswana'),
        Country(code='BV', name='Bouvet Island'),
        Country(code='BR', name='Brazil'),
        Country(code='BN', name='Brunei Darussalam'),
        Country(code='BG', name='Bulgaria'),
        Country(code='BF', name='Burkina Faso'),
        Country(code='BI', name='Burundi'),
        Country(code='KH', name='Cambodia'),
        Country(code='CM', name='Cameroon'),
        Country(code='CA', name='Canada'),
        Country(code='CV', name='Cape Verde'),
        Country(code='KY', name='Cayman Islands'),
        Country(code='CF', name='Central African Rep'),
        Country(code='TD', name='Chad'),
        Country(code='CL', name='Chile'),
        Country(code='CN', name='China'),
        Country(code='CX', name='Christmas Island'),
        Country(code='CC', name='Cocos Islands'),
        Country(code='CO', name='Colombia'),
        Country(code='KM', name='Comoros'),
        Country(code='CG', name='Congo'),
        Country(code='CK', name='Cook Islands'),
        Country(code='CR', name='Costa Rica'),
        Country(code='CI', name='Cote D`ivoire'),
        Country(code='HR', name='Croatia'),
        Country(code='CU', name='Cuba'),
        Country(code='CY', name='Cyprus'),
        Country(code='CZ', name='Czech Republic'),
        Country(code='DK', name='Denmark'),
        Country(code='DJ', name='Djibouti'),
        Country(code='DM', name='Dominica'),
        Country(code='DO', name='Dominican Republic'),
        Country(code='TP', name='East Timor'),
        Country(code='EC', name='Ecuador'),
        Country(code='EG', name='Egypt'),
        Country(code='SV', name='El Salvador'),
        Country(code='GQ', name='Equatorial Guinea'),
        Country(code='ER', name='Eritrea'),
        Country(code='EE', name='Estonia'),
        Country(code='ET', name='Ethiopia'),
        Country(code='FK', name='Falkland Islands (Malvinas)'),
        Country(code='FO', name='Faroe Islands'),
        Country(code='FJ', name='Fiji'),
        Country(code='FI', name='Finland'),
        Country(code='FR', name='France'),
        Country(code='GF', name='French Guiana'),
        Country(code='PF', name='French Polynesia'),
        Country(code='TF', name='French S. Territories'),
        Country(code='GA', name='Gabon'),
        Country(code='GM', name='Gambia'),
        Country(code='GE', name='Georgia'),
        Country(code='DE', name='Germany'),
        Country(code='GH', name='Ghana'),
        Country(code='GI', name='Gibraltar'),
        Country(code='GR', name='Greece'),
        Country(code='GL', name='Greenland'),
        Country(code='GD', name='Grenada'),
        Country(code='GP', name='Guadeloupe'),
        Country(code='GU', name='Guam'),
        Country(code='GT', name='Guatemala'),
        Country(code='GN', name='Guinea'),
        Country(code='GW', name='Guinea-bissau'),
        Country(code='GY', name='Guyana'),
        Country(code='HT', name='Haiti'),
        Country(code='HN', name='Honduras'),
        Country(code='HK', name='Hong Kong'),
        Country(code='HU', name='Hungary'),
        Country(code='IS', name='Iceland'),
        Country(code='IN', name='India'),
        Country(code='ID', name='Indonesia'),
        Country(code='IR', name='Iran'),
        Country(code='IQ', name='Iraq'),
        Country(code='IE', name='Ireland'),
        Country(code='IL', name='Israel'),
        Country(code='IT', name='Italy'),
        Country(code='JM', name='Jamaica'),
        Country(code='JP', name='Japan'),
        Country(code='JO', name='Jordan'),
        Country(code='KZ', name='Kazakhstan'),
        Country(code='KE', name='Kenya'),
        Country(code='KI', name='Kiribati'),
        Country(code='KP', name='Korea (North)'),
        Country(code='KR', name='Korea (South)'),
        Country(code='KW', name='Kuwait'),
        Country(code='KG', name='Kyrgyzstan'),
        Country(code='LA', name='Laos'),
        Country(code='LV', name='Latvia'),
        Country(code='LB', name='Lebanon'),
        Country(code='LS', name='Lesotho'),
        Country(code='LR', name='Liberia'),
        Country(code='LY', name='Libya'),
        Country(code='LI', name='Liechtenstein'),
        Country(code='LT', name='Lithuania'),
        Country(code='LU', name='Luxembourg'),
        Country(code='MO', name='Macau'),
        Country(code='MK', name='Macedonia'),
        Country(code='MG', name='Madagascar'),
        Country(code='MW', name='Malawi'),
        Country(code='MY', name='Malaysia'),
        Country(code='MV', name='Maldives'),
        Country(code='ML', name='Mali'),
        Country(code='MT', name='Malta'),
        Country(code='MH', name='Marshall Islands'),
        Country(code='MQ', name='Martinique'),
        Country(code='MR', name='Mauritania'),
        Country(code='MU', name='Mauritius'),
        Country(code='YT', name='Mayotte'),
        Country(code='MX', name='Mexico'),
        Country(code='FM', name='Micronesia'),
        Country(code='MD', name='Moldova'),
        Country(code='MC', name='Monaco'),
        Country(code='MN', name='Mongolia'),
        Country(code='MS', name='Montserrat'),
        Country(code='MA', name='Morocco'),
        Country(code='MZ', name='Mozambique'),
        Country(code='MM', name='Myanmar'),
        Country(code='NA', name='Namibia'),
        Country(code='NR', name='Nauru'),
        Country(code='NP', name='Nepal'),
        Country(code='NL', name='Netherlands'),
        Country(code='AN', name='Netherlands Antilles'),
        Country(code='NC', name='New Caledonia'),
        Country(code='NZ', name='New Zealand'),
        Country(code='NI', name='Nicaragua'),
        Country(code='NE', name='Niger'),
        Country(code='NG', name='Nigeria'),
        Country(code='NU', name='Niue'),
        Country(code='NF', name='Norfolk Island'),
        Country(code='MP', name='Northern Mariana Islands'),
        Country(code='NO', name='Norway'),
        Country(code='OM', name='Oman'),
        Country(code='PK', name='Pakistan'),
        Country(code='PW', name='Palau'),
        Country(code='PA', name='Panama'),
        Country(code='PG', name='Papua New Guinea'),
        Country(code='PY', name='Paraguay'),
        Country(code='PE', name='Peru'),
        Country(code='PH', name='Philippines'),
        Country(code='PN', name='Pitcairn'),
        Country(code='PL', name='Poland'),
        Country(code='PT', name='Portugal'),
        Country(code='PR', name='Puerto Rico'),
        Country(code='QA', name='Qatar'),
        Country(code='RE', name='Reunion'),
        Country(code='RO', name='Romania'),
        Country(code='RU', name='Russian Federation'),
        Country(code='RW', name='Rwanda'),
        Country(code='KN', name='Saint Kitts And Nevis'),
        Country(code='LC', name='Saint Lucia'),
        Country(code='VC', name='St Vincent/Grenadines'),
        Country(code='WS', name='Samoa'),
        Country(code='SM', name='San Marino'),
        Country(code='ST', name='Sao Tome'),
        Country(code='SA', name='Saudi Arabia'),
        Country(code='SN', name='Senegal'),
        Country(code='SC', name='Seychelles'),
        Country(code='SL', name='Sierra Leone'),
        Country(code='SG', name='Singapore'),
        Country(code='SK', name='Slovakia'),
        Country(code='SI', name='Slovenia'),
        Country(code='SB', name='Solomon Islands'),
        Country(code='SO', name='Somalia'),
        Country(code='ZA', name='South Africa'),
        Country(code='ES', name='Spain'),
        Country(code='LK', name='Sri Lanka'),
        Country(code='SH', name='St. Helena'),
        Country(code='PM', name='St.Pierre'),
        Country(code='SD', name='Sudan'),
        Country(code='SR', name='Suriname'),
        Country(code='SZ', name='Swaziland'),
        Country(code='SE', name='Sweden'),
        Country(code='CH', name='Switzerland'),
        Country(code='SY', name='Syrian Arab Republic'),
        Country(code='TW', name='Taiwan'),
        Country(code='TJ', name='Tajikistan'),
        Country(code='TZ', name='Tanzania'),
        Country(code='TH', name='Thailand'),
        Country(code='TG', name='Togo'),
        Country(code='TK', name='Tokelau'),
        Country(code='TO', name='Tonga'),
        Country(code='TT', name='Trinidad And Tobago'),
        Country(code='TN', name='Tunisia'),
        Country(code='TR', name='Turkey'),
        Country(code='TM', name='Turkmenistan'),
        Country(code='TV', name='Tuvalu'),
        Country(code='UG', name='Uganda'),
        Country(code='UA', name='Ukraine'),
        Country(code='US', name='United States'),
        Country(code='AE', name='United Arab Emirates'),
        Country(code='UK', name='United Kingdom'),
        Country(code='UY', name='Uruguay'),
        Country(code='UZ', name='Uzbekistan'),
        Country(code='VU', name='Vanuatu'),
        Country(code='VA', name='Vatican City State'),
        Country(code='VE', name='Venezuela'),
        Country(code='VN', name='Viet Nam'),
        Country(code='VG', name='Virgin Islands (British)'),
        Country(code='VI', name='Virgin Islands (U.S.)'),
        Country(code='EH', name='Western Sahara'),
        Country(code='YE', name='Yemen'),
        Country(code='YU', name='Yugoslavia'),
        Country(code='ZR', name='Zaire'),
        Country(code='ZM', name='Zambia'),
        Country(code='ZW', name='Zimbabwe'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_countires),
    ]